{% set version = "0.9.4" %}

package:
  name: compass-interface-core
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface-core/releases/download/v{{ version }}/compass-interface-core-{{ version }}.tar.gz
  sha256: 224108697b0c03d3677f59c0efb3666308576fb1f7fed87325227d2585b3a80f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - requests
    - lxml
    - pydantic
    - email-validator
    - phonenumbers

test:
  imports:
    - compass

about:
  home: https://github.com/the-scouts/compass-interface-core
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
  dev_url: https://github.com/the-scouts/compass-interface-core

extra:
  recipe-maintainers:
    - AA-Turner
    - rglss
