{% set version = "0.10.2" %}

package:
  name: compass-interface-core
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface-core/releases/download/v{{ version }}/compass-interface-core-{{ version }}.tar.gz
  sha256: 10e72dca504d4006fdc12a35706c1bda2a61c4604111e0e9460a42e78cf7b160

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - requests
    - lxml
    - pydantic
    - email-validator
    - phonenumbers

test:
  imports:
    - compass

about:
  home: https://github.com/the-scouts/compass-interface-core
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
  dev_url: https://github.com/the-scouts/compass-interface-core

extra:
  recipe-maintainers:
    - AA-Turner
    - rglss
