{% set version = "0.13.0" %}

package:
  name: compass-interface-core
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface-core/releases/download/v{{ version }}/compass-interface-core-{{ version }}.tar.gz
  sha256: 2e56eec5b0c6ce3f56dee94654cc5b00c7bcfa8e2a237b592733513c33750ade

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - requests
    - lxml
    - pydantic
    - email-validator
    - phonenumbers

test:
  imports:
    - compass

about:
  home: https://github.com/the-scouts/compass-interface-core
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
  dev_url: https://github.com/the-scouts/compass-interface-core

extra:
  recipe-maintainers:
    - AA-Turner
    - rglss
