{% set version = "0.10.0" %}

package:
  name: compass-interface-core
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface-core/releases/download/v{{ version }}/compass-interface-core-{{ version }}.tar.gz
  sha256: 97c1111286da25a8cbc825e36896fe7fe933bead3f03ea48c7f6b8efb7ff9d6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - requests
    - lxml
    - pydantic
    - email-validator
    - phonenumbers

test:
  imports:
    - compass

about:
  home: https://github.com/the-scouts/compass-interface-core
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
  dev_url: https://github.com/the-scouts/compass-interface-core

extra:
  recipe-maintainers:
    - AA-Turner
    - rglss
